### ISSUE TITLE
object reference not set to an instance of an object

### ISSUE THREAD

**Issue by herecydev** [nicbell/ucreate#21]
At [this line](https://github.com/nicbell/ucreate/blob/bffae217d35af673226225d84ba207172e90891d/NicBell.UCreate/Sync/BaseTreeContentTypeSync.cs#L28) there are some checks for "expected" base classes. If, however, you supply a base class for example:

```c#
public class Foo {
        public int Bar{ get; set; }
}

[DocType(Name = "Some Content")]
public class MyDocType : Foo {
     [Property(Alias = nameof(Title), Name = "Title", TypeName = PropertyTypes.Textstring)]
        public string Title { get; set; }
}
```

The UCreate `SyncAll` method then proceeds to raise a null reference exception. I assume therefore using inheritance is not permitted as-is unless you are using `PublishedContentModel`. It would be nice to either allow that or throw a more helpful exception to the consumer.

**Comment by nicbell** [comment]
You are correct, one class can inherit from another as long as at some point the base class is `PublishedContentModel` for classes with the `DocType` attribute, here is an [example](https://github.com/nicbell/ucreate#doctype-example). Doc types need this for various reasons.

`MediaType` doesn't need this, here is an [example](https://github.com/nicbell/ucreate#mediatype-example)

That check is only for finding first level types for docs and media. I should probably do a more specific check in [DocTypeSync](https://github.com/nicbell/ucreate/blob/master/NicBell.UCreate/Sync/DocTypeSync.cs).

**Comment by herecydev** [comment]
> Doc types need this for various reasons.

Could you elaborate on this please? In our use case, we want the `Foo` base class to be there so we can set some additional properties. `PublishedContentModel` has too much that we would rather no expose. It might be worth saying that if we add the base class *after* ucreate has been run then obviously it doesn't cause any exceptions to be raised as the work to create it in Umbraco has been done and we then have our `Foo` base class working and we can set properties. But that's not ideal as recreating in another environment would then raise exceptions again.

It feels to me that ucreate should be able to safely ignore this. What are your thoughts?

**Comment by nicbell** [comment]
I see. The main reason to use `PublishedContentModel` is for strongly-typed views, which is not really applicable here as it seems you won't be using them. 

The check is actually trying to collected first level types because doc types have to be synced as a tree otherwise Umbraco could try create a child before the parent and get upset. The check assumes your top levels types will either inherit from `PublishedContentModel` or nothing but in your case it's `Foo`.

I guess there are a few solutions for this. When searching for first level types I could try find any class that has `DocTypeAttribute` where it's base class doesn't have `DocTypeAttribute`. Another way would be for the behaviour that your are getting from `Foo` could be got via composition over inheritance.

**Comment by nicbell** [comment]
`2.0.3` should appear on Nuget soon, let me know if it fixes the issue.

**Comment by nicbell** [comment]
@herecydev did this fix work for you?

**Comment by herecydev** [comment]
Hi @nicbell we're going to be testing this internally ASAP. If you can keep this ticket open, I'll get back with some feedback soon.

**Comment by herecydev** [comment]
Hey @nicbell this seems to work exactly as advertised. Thank you very much for getting on this and providing a quick release to us!
