### ISSUE TITLE
Masterpage Templates

### ISSUE THREAD

**Issue by kipusoep** [nicbell/ucreate#6]
This issue is about using masterpages as templates in umbraco.

I was looking for a way to automatically register new templates in umbraco by using UCreate, just like one would create new DocTypes, but didn't find one.
So I just created a new masterpage template called Test, which derives from my 'MasterPage.master' inside Visual Studio.
Then I referenced this template in one of my UCreate DocTypes and fired up a browser to visit umbraco and see what happens.
The result is that the Test masterpage gets registered in Umbraco, but the content is overwritten because of `NicBell.UCreate.Sync.CreateTemplate()`.
Also the template is registered in the root, instead of underneath the derived masterpage 'MasterPage'.

**Comment by nicbell** [comment]
Thanks for reporting this.
Are you using 0.0.22 with webforms?
The doc types should generate any referenced templates only if they don't already exist but I have only tested it with razor.

**Comment by kipusoep** [comment]
Yes Webforms it is :-)
I can help fix this?

Op 11 nov. 2015 om 12:16 heeft Nic Bell notifications@github.com het
volgende geschreven:

Thanks for reporting this.
Are you using 0.0.22 with webforms?
The doc types should generate any referenced templates only if they don't
already exist but I have only tested it with razor.

**Comment by nicbell** [comment]
I had no idea anyone was still using Webforms. :P. 
I have just written a fix, just testing it, should be deployed and on Nuget within the next hour.

**Comment by kipusoep** [comment]
Thanks, I'll try it later today :-)

**Comment by nicbell** [comment]
0.0.23 is now on Nuget. :shipit:

**Comment by kipusoep** [comment]
It's working, though the template is registered in the root, instead of underneath it's Master masterpage.

**Comment by nicbell** [comment]
I'm glad it's working.

The nesting is a bit weird, it's determined by how a user nests templates when creating them in Umbraco rather than the actual code inside the templates.

If a user creates two root master pages in Umbraco called `A` and `B` then creates `C` under `B` but later changes the code in `C` to be under `A`, `C` will still appear under `B` in Umbraco.

So because Umbraco doesn't actually parse the templates to create the structure the only way for UCreate to build the structure would be by using regex on the template code to determine how the templates relate to each other. How valuable a feature do you think this will be?

**Comment by kipusoep** [comment]
You're right, it doesn't matter at all how it's displayed in Umbraco :-)

------ Origineel bericht ------
Van: "Nic Bell" notifications@github.com
Aan: "nicbell/ucreate" ucreate@noreply.github.com
CC: "Stefan Kip" mail@kipusoep.nl
Verzonden: 11-11-2015 18:29:34
Onderwerp: Re: [ucreate] Masterpage Templates (#6)
